%% lecture2_population_field_lowrank_demo.m
% Classroom MATLAB demo for Lecture 2.
%
% Revised emphasis: neural fields and population-rate models only.
%
% Blocks:
%   A) Wilson-Cowan E-I dynamics as the non-spatial bridge.
%   B) Ring neural field with a persistent bump / continuous attractor.
%   C) Traveling bump generated by a small asymmetry in the kernel.
%   D) Pattern formation (multi-bump state) from Mexican-hat interactions.
%
% Pedagogical message:
%   single-neuron / population descriptions -> rate models -> spatial fields.
%   Symmetry gives continuous attractors; asymmetry gives motion; lateral
%   inhibition selects patterns.
%
% The script is self-contained and uses only core MATLAB.
% It is meant for lecture demos, not quantitative data fitting.

clear; close all; clc;
rng(3);

RUN_WILSON_COWAN   = true;
RUN_CONT_ATTR      = true;
RUN_TRAVELING_WAVE = true;
RUN_PATTERN_FORM   = true;

%% ------------------------------------------------------------------------
% A. Wilson-Cowan E-I population model
% -------------------------------------------------------------------------

if RUN_WILSON_COWAN
    wc = struct();
    wc.tauE  = 8.0;
    wc.tauI  = 12.0;
    wc.wEE   = 12.0;
    wc.wEI   = 10.0;
    wc.wIE   = 10.0;
    wc.wII   = 0.0;
    wc.P     = 1.5;
    wc.Q     = 0.0;
    wc.a     = 1.3;
    wc.theta = 2.5;

    dtWC = 0.1;
    TWC  = 300.0;
    [tWC, EWC, IWC] = simulateWilsonCowan(TWC, dtWC, wc);

    Egrid = linspace(1e-3, 1-1e-3, 500);
    I_null_E = (wc.wEE * Egrid + wc.P - invSigmoid(Egrid, wc.a, wc.theta)) / wc.wEI;
    I_null_I = sigmoidWC(wc.wIE * Egrid + wc.Q, wc.a, wc.theta);

    figure('Name', 'Lecture 2A: Wilson-Cowan bridge', ...
           'Color', 'w', 'Position', [80 80 1050 680]);

    subplot(2,1,1);
    plot(tWC, EWC, 'LineWidth', 1.8); hold on;
    plot(tWC, IWC, 'LineWidth', 1.8);
    xlabel('Time'); ylabel('Activity');
    legend({'E(t)', 'I(t)'}, 'Location', 'best');
    title('Wilson-Cowan: a spatially lumped population model');
    box off;

    subplot(2,1,2);
    plot(Egrid, I_null_E, 'LineWidth', 1.8); hold on;
    plot(Egrid, I_null_I, '--', 'LineWidth', 1.8);
    plot(EWC, IWC, 'k', 'LineWidth', 1.2);
    xlabel('E'); ylabel('I');
    legend({'E-nullcline', 'I-nullcline', 'Trajectory'}, 'Location', 'best');
    title('Phase plane: the field becomes an ODE when space is collapsed');
    axis([0 1 0 1]);
    box off;
end

%% ------------------------------------------------------------------------
% B. Persistent bump + continuous attractor on a ring
% -------------------------------------------------------------------------

if RUN_CONT_ATTR
    ca = defaultRingFieldPars();
    ca.T = 70.0;
    ca.schedule = [ ...
        0.0,  8.0, 0.20, 0.040, 0.80; ...  % build a bump
        25.0, 33.0, 0.55, 0.050, 0.45];    % nudge it to a new location

    [xCA, tCA, uCA, rCA, ~, rFinalCA] = simulateRingField(ca);
    centerCA = computeRingCenterTrajectory(xCA, rCA, ca.L);

    cueCenters = [0.15, 0.35, 0.55, 0.75];
    familyProfiles = zeros(ca.N, numel(cueCenters));
    for j = 1:numel(cueCenters)
        pTmp = ca;
        pTmp.T = 40.0;
        pTmp.schedule = [0.0, 8.0, cueCenters(j), 0.040, 0.80];
        [~, ~, ~, ~, ~, rEnd] = simulateRingField(pTmp);
        familyProfiles(:, j) = rEnd;
    end

    figure('Name', 'Lecture 2B: Continuous attractor', ...
           'Color', 'w', 'Position', [100 100 1150 760]);

    subplot(2,2,1);
    imagesc(tCA, xCA, uCA);
    axis xy;
    xlabel('Time'); ylabel('Position x');
    title('Localized cue creates a persistent bump');
    colorbar;

    subplot(2,2,2);
    plot(tCA, centerCA, 'LineWidth', 1.8);
    xlabel('Time'); ylabel('Bump center');
    ylim([0 ca.L]);
    title('A transient cue repositions the bump on a neutral manifold');
    box off;

    subplot(2,2,[3 4]);
    plot(xCA, familyProfiles, 'LineWidth', 1.8);
    xlabel('Position x'); ylabel('Firing rate r(x)');
    title('Continuous attractor: same bump shape, different positions on the ring');
    legend({'cue at 0.15', 'cue at 0.35', 'cue at 0.55', 'cue at 0.75'}, ...
           'Location', 'best');
    box off;

    fprintf('\nContinuous attractor demo:\n');
    fprintf('  A translation-symmetric ring supports a family of equivalent bump states.\n');
    fprintf('  The first cue creates the bump; the second cue shifts it without changing its shape much.\n');
end

%% ------------------------------------------------------------------------
% C. Traveling wave / moving bump from a weak asymmetry in connectivity
% -------------------------------------------------------------------------

if RUN_TRAVELING_WAVE
    tw = defaultRingFieldPars();
    tw.T = 120.0;
    tw.delta = 0.012;     % shift the kernel slightly forward on the ring
    tw.schedule = [0.0, 6.0, 0.25, 0.040, 0.80];

    [xTW, tTW, uTW, rTW] = simulateRingField(tw);
    centerTW = computeRingCenterTrajectory(xTW, rTW, tw.L);
    centerTWunwrapped = unwrap(2 * pi * centerTW / tw.L) * tw.L / (2 * pi);

    fitMask = tTW >= 20.0;
    speedFit = polyfit(tTW(fitMask), centerTWunwrapped(fitMask), 1);
    waveSpeed = speedFit(1);

    figure('Name', 'Lecture 2C: Traveling bump', ...
           'Color', 'w', 'Position', [120 120 1100 760]);

    subplot(3,1,1);
    [dKernel, wSym] = makeRingKernel(tw.N, tw.L, tw.Ae, tw.Ai, tw.sigmaE, tw.sigmaI, 0.0);
    [~,      wAsy] = makeRingKernel(tw.N, tw.L, tw.Ae, tw.Ai, tw.sigmaE, tw.sigmaI, tw.delta);
    plot(dKernel, wSym, 'LineWidth', 1.6); hold on;
    plot(dKernel, wAsy, '--', 'LineWidth', 1.6);
    xlabel('Signed displacement'); ylabel('w(\Delta x)');
    legend({'symmetric kernel', 'shifted kernel'}, 'Location', 'best');
    title('A tiny asymmetry biases activity to move around the ring');
    box off;

    subplot(3,1,2);
    imagesc(tTW, xTW, uTW);
    axis xy;
    xlabel('Time'); ylabel('Position x');
    title('Traveling wave / moving bump in the neural field');
    colorbar;

    subplot(3,1,3);
    plot(tTW, centerTWunwrapped, 'LineWidth', 1.8);
    xlabel('Time'); ylabel('Unwrapped bump position');
    title(sprintf('Approximate wave speed = %.4f positions per unit time', waveSpeed));
    box off;

    fprintf('\nTraveling-wave demo:\n');
    fprintf('  A symmetric kernel gives a stationary bump.\n');
    fprintf('  A small shift in the kernel breaks left-right symmetry and produces a moving bump.\n');
    fprintf('  Estimated speed: %.4f positions / unit time.\n', waveSpeed);
end

%% ------------------------------------------------------------------------
% D. Pattern formation: symmetry breaking and multi-bump states
% -------------------------------------------------------------------------

if RUN_PATTERN_FORM
    pf = defaultRingFieldPars();
    pf.T = 120.0;
    pf.h = 0.15;                 % tonic drive lifts the uniform state near threshold
    pf.beta = 80.0;
    pf.u0 = 0.01 * randn(pf.N, 1);
    pf.schedule = [];

    [xPF, tPF, uPF, rPF, ~, rFinalPF] = simulateRingField(pf);

    fftMag = abs(fft(rFinalPF - mean(rFinalPF)));
    halfIdx = 2:floor(pf.N/2);
    [~, idxMax] = max(fftMag(halfIdx));
    dominantMode = halfIdx(idxMax) - 1;
    nPeaks = countPeaksPeriodic(rFinalPF, mean(rFinalPF) + 0.25 * (max(rFinalPF) - mean(rFinalPF)));

    figure('Name', 'Lecture 2D: Pattern formation', ...
           'Color', 'w', 'Position', [140 140 1150 760]);

    subplot(2,2,[1 3]);
    imagesc(tPF, xPF, uPF);
    axis xy;
    xlabel('Time'); ylabel('Position x');
    title('Small spatial inhomogeneities grow into a patterned state');
    colorbar;

    subplot(2,2,2);
    plot(xPF, rFinalPF, 'LineWidth', 2.0);
    xlabel('Position x'); ylabel('Final firing rate');
    title(sprintf('Final multi-bump pattern (%d visible peaks)', nPeaks));
    box off;

    subplot(2,2,4);
    stem(0:12, fftMag(1:13), 'filled');
    xlabel('Spatial Fourier mode'); ylabel('|\hat{r}_k|');
    title(sprintf('Dominant selected mode: k = %d', dominantMode));
    box off;

    fprintf('\nPattern-formation demo:\n');
    fprintf('  Local excitation + broader inhibition destabilize the uniform state.\n');
    fprintf('  The field selects a spatial mode and settles into a multi-bump pattern.\n');
    fprintf('  Dominant Fourier mode: k = %d. Visible peaks: %d.\n', dominantMode, nPeaks);
end

fprintf('\nLecture 2 demo summary:\n');
fprintf('  Wilson-Cowan: non-spatial population dynamics as a bridge to fields.\n');
fprintf('  Continuous attractor: persistent bump + neutral translation on a ring.\n');
fprintf('  Traveling wave: asymmetry converts a stationary bump into a moving one.\n');
fprintf('  Pattern formation: Mexican-hat interactions select spatial structure.\n');

%% ------------------------------------------------------------------------
% End of main script. Local functions below.
% -------------------------------------------------------------------------

function p = defaultRingFieldPars()
    p = struct();
    p.N          = 256;
    p.L          = 1.0;
    p.dt         = 0.02;
    p.T          = 80.0;
    p.tau        = 1.0;
    p.Ae         = 18.0;
    p.Ai         = 12.0;
    p.sigmaE     = 0.05;
    p.sigmaI     = 0.18;
    p.delta      = 0.0;
    p.beta       = 60.0;
    p.theta      = 0.15;
    p.h          = 0.0;
    p.storeEvery = 25;
    p.schedule   = [];
    p.u0         = [];
end

function [t, E, I] = simulateWilsonCowan(T, dt, p)
    nSteps = round(T / dt) + 1;
    t = (0:nSteps-1) * dt;
    E = zeros(1, nSteps);
    I = zeros(1, nSteps);

    E(1) = 0.15;
    I(1) = 0.05;

    for k = 1:nSteps-1
        dE = (-E(k) + sigmoidWC(p.wEE * E(k) - p.wEI * I(k) + p.P, p.a, p.theta)) / p.tauE;
        dI = (-I(k) + sigmoidWC(p.wIE * E(k) - p.wII * I(k) + p.Q, p.a, p.theta)) / p.tauI;
        E(k+1) = E(k) + dt * dE;
        I(k+1) = I(k) + dt * dI;
    end
end

function y = sigmoidWC(x, a, theta)
    z = -a * (x - theta);
    z = max(min(z, 60), -60);
    y = 1.0 ./ (1.0 + exp(z));
end

function x = invSigmoid(y, a, theta)
    x = theta + (1.0 / a) * log(y ./ (1.0 - y));
end

function [xGrid, tStore, uStore, rStore, uFinal, rFinal] = simulateRingField(p)
    xGrid = (0:p.N-1).' / p.N * p.L;
    dx = p.L / p.N;

    [~, kernel] = makeRingKernel(p.N, p.L, p.Ae, p.Ai, p.sigmaE, p.sigmaI, p.delta);
    Wfft = fft(kernel);

    if isempty(p.u0)
        u = zeros(p.N, 1);
    else
        u = p.u0(:);
    end

    nSteps = round(p.T / p.dt) + 1;
    nStoreMax = floor((nSteps - 1) / p.storeEvery) + 2;
    uStore = zeros(p.N, nStoreMax);
    rStore = zeros(p.N, nStoreMax);
    tStore = zeros(1, nStoreMax);

    r = sigmoidField(u, p.beta, p.theta);
    storeIdx = 1;
    uStore(:, storeIdx) = u;
    rStore(:, storeIdx) = r;
    tStore(storeIdx) = 0.0;

    for k = 1:nSteps-1
        tNow = (k-1) * p.dt;
        Iext = buildRingStimulus(xGrid, tNow, p.schedule, p.L) + p.h;

        convTerm = real(ifft(fft(r) .* Wfft)) * dx;
        du = (-u + convTerm + Iext) / p.tau;
        u = u + p.dt * du;
        r = sigmoidField(u, p.beta, p.theta);

        if mod(k, p.storeEvery) == 0 || k == (nSteps - 1)
            storeIdx = storeIdx + 1;
            uStore(:, storeIdx) = u;
            rStore(:, storeIdx) = r;
            tStore(storeIdx) = k * p.dt;
        end
    end

    uStore = uStore(:, 1:storeIdx);
    rStore = rStore(:, 1:storeIdx);
    tStore = tStore(1:storeIdx);
    uFinal = u;
    rFinal = r;
end

function Iext = buildRingStimulus(xGrid, tNow, schedule, L)
    Iext = zeros(size(xGrid));
    if isempty(schedule)
        return;
    end

    for j = 1:size(schedule, 1)
        tOn = schedule(j, 1);
        tOff = schedule(j, 2);
        center = schedule(j, 3);
        width = schedule(j, 4);
        amp = schedule(j, 5);

        if tNow >= tOn && tNow < tOff
            d = periodicDistance(xGrid, center, L);
            Iext = Iext + amp * exp(-(d.^2) / (2 * width^2));
        end
    end
end

function d = periodicDistance(xGrid, center, L)
    d = abs(mod(xGrid - center + L/2, L) - L/2);
end

function [dSigned, kernel] = makeRingKernel(N, L, Ae, Ai, sigmaE, sigmaI, delta)
    dSigned = (0:N-1).' / N * L;
    dSigned = mod(dSigned + L/2, L) - L/2;

    kernel = Ae * exp(-((dSigned - delta).^2) / (2 * sigmaE^2)) ...
           - Ai * exp(-((dSigned - delta).^2) / (2 * sigmaI^2));
end

function r = sigmoidField(u, beta, theta)
    z = -beta * (u - theta);
    z = max(min(z, 60), -60);
    r = 1.0 ./ (1.0 + exp(z));
end

function center = computeRingCenterTrajectory(xGrid, rStore, L)
    nTimes = size(rStore, 2);
    center = nan(1, nTimes);
    zGrid = exp(1i * 2 * pi * xGrid / L);

    for k = 1:nTimes
        r = rStore(:, k);
        if sum(r) < 1e-6 || (max(r) - min(r)) < 1e-4
            center(k) = NaN;
        else
            z = sum(r .* zGrid);
            if abs(z) < 1e-8 * sum(r)
                center(k) = NaN;
            else
                center(k) = mod(angle(z), 2*pi) * L / (2*pi);
            end
        end
    end

    if any(isnan(center))
        idx = find(~isnan(center), 1, 'first');
        if ~isempty(idx)
            center(1:idx-1) = center(idx);
            for k = idx+1:nTimes
                if isnan(center(k))
                    center(k) = center(k-1);
                end
            end
        end
    end
end

function nPeaks = countPeaksPeriodic(y, threshold)
    yPrev = y([end, 1:end-1]);
    yNext = y([2:end, 1]);
    mask = (y > yPrev) & (y >= yNext) & (y > threshold);
    nPeaks = sum(mask);
end
